# Generated by Django 5.1.1 on 2026-04-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='На распродаже'),
        ),
    ]
