# Generated by Django 5.1.1 on 2026-04-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_is_sale_alter_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='is_selected',
            field=models.BooleanField(default=True, verbose_name='Купить'),
        ),
    ]
