# Generated by Django 5.1.1 on 2026-05-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Оплачен'), ('collecting', 'Собирается на складе'), ('pick_up', 'Можно забирать'), ('shipped', 'Доставлен'), ('cancelled', 'Отменен')], default='paid', max_length=50, verbose_name='Статус'),
        ),
    ]
